// Command genchroma writes static/css/chroma.css with class-based syntax
// highlighting for both light and dark themes. Dark rules are scoped under
// [data-theme="dark"]. Run with: go run ./tools/genchroma
package main

import (
	"bufio"
	"log"
	"os"
	"strings"

	"github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"
)

func main() {
	out, err := os.Create("static/css/chroma.css")
	if err != nil {
		log.Fatal(err)
	}
	defer out.Close()

	w := bufio.NewWriter(out)
	defer w.Flush()

	light := html.New(html.WithClasses(true))
	dark := html.New(html.WithClasses(true))

	w.WriteString("/* generated by tools/genchroma -- do not edit by hand */\n")

	// chroma v2.26 namespaces selectors with the style's theme variant class
	// (.chroma.light / .chroma.dark), but goldmark renders only class="chroma".
	// Strip the variant class so the rules actually match.
	var lbuf strings.Builder
	if err := light.WriteCSS(&lbuf, styles.Get("github")); err != nil {
		log.Fatal(err)
	}
	w.WriteString(strings.ReplaceAll(lbuf.String(), ".light", ""))

	// Capture dark CSS, strip its variant class, then scope under [data-theme="dark"].
	var dbuf strings.Builder
	if err := dark.WriteCSS(&dbuf, styles.Get("github-dark")); err != nil {
		log.Fatal(err)
	}
	w.WriteString("\n")
	for _, line := range strings.Split(strings.ReplaceAll(dbuf.String(), ".dark", ""), "\n") {
		w.WriteString(scopeDark(line))
		w.WriteString("\n")
	}
}

// scopeDark prefixes a chroma CSS rule's selectors with [data-theme="dark"].
// chroma emits one rule per line; selectors begin with "." (optionally after a
// "/* comment */ " prefix).
func scopeDark(line string) string {
	if strings.TrimSpace(line) == "" {
		return line
	}
	prefix := ""
	rest := line
	if i := strings.Index(line, "*/"); strings.HasPrefix(strings.TrimSpace(line), "/*") && i != -1 {
		prefix = line[:i+2] + " "
		rest = strings.TrimSpace(line[i+2:])
	}
	if !strings.HasPrefix(rest, ".") {
		return line
	}
	// A rule may have comma-separated selectors before the "{".
	brace := strings.Index(rest, "{")
	if brace == -1 {
		return prefix + `[data-theme="dark"] ` + rest
	}
	selectors := strings.Split(rest[:brace], ",")
	for i, s := range selectors {
		selectors[i] = `[data-theme="dark"] ` + strings.TrimSpace(s)
	}
	return prefix + strings.Join(selectors, ", ") + " " + rest[brace:]
}
