package view

import (
	"encoding/json"
	"html/template"
	"time"

	"github.com/ZdsAlpha/web/internal/content"
)

const authorName = "Abdul Rahman"

// authorSameAs lists the author's canonical profiles elsewhere, used to link the
// Person entity to off-site identities (helps Google entity understanding).
var authorSameAs = []string{"https://github.com/ZdsAlpha"}

// Head carries everything the shared Layout needs to render <head>. Building it
// in Go (rather than threading many positional args through templ) keeps the
// meta + JSON-LD construction testable and escaping-safe.
type Head struct {
	Title       string
	Description string
	Path        string    // absolute path for canonical/og:url; "" omits them
	OGType      string    // "website" (default) or "article"
	Published   time.Time // posts only; zero => omitted
	Modified    time.Time // posts only; zero => omitted
	Tags        []string  // posts only; emitted as article:tag
	JSONLD      []template.HTML
}

// ogImage returns the absolute URL of the shared social-share card, or "" when
// no base URL is configured (which suppresses the image tags). The card is a
// committed static asset regenerated by `go run ./tools/genog`.
func ogImage() string { return canonical("/static/og/default.png") }

func (h Head) ogType() string {
	if h.OGType == "" {
		return "website"
	}
	return h.OGType
}

// HomeHead builds the head metadata + JSON-LD for the site homepage.
func HomeHead(title, desc string) Head {
	return Head{
		Title:       title,
		Description: desc,
		Path:        "/",
		JSONLD:      []template.HTML{websiteLD(), personLD()},
	}
}

// PostHead builds article metadata + BlogPosting/BreadcrumbList JSON-LD for a post.
func PostHead(p *content.Post) Head {
	return Head{
		Title:       p.Title + " — " + authorName,
		Description: p.Description,
		Path:        "/posts/" + p.Slug,
		OGType:      "article",
		Published:   p.Date,
		Tags:        p.Tags,
		JSONLD:      []template.HTML{blogPostingLD(p), breadcrumbLD(p.Title, "/posts/"+p.Slug)},
	}
}

// PageHead builds the head metadata for a standalone page.
func PageHead(p *content.Page) Head {
	return Head{
		Title:       p.Title + " — " + authorName,
		Description: p.Description,
		Path:        "/" + p.Slug,
	}
}

// ldScript marshals v to JSON and wraps it in a <script type="application/ld+json">
// block. encoding/json escapes <, >, and & to \u00xx by default, so the result
// is safe to embed inline (no </script> breakout) and is rendered via templ.Raw.
// As inert data — not executable JS — it is unaffected by the strict CSP.
func ldScript(v any) template.HTML {
	b, err := json.Marshal(v)
	if err != nil {
		return ""
	}
	return template.HTML(`<script type="application/ld+json">` + string(b) + `</script>`)
}

func websiteLD() template.HTML {
	return ldScript(map[string]any{
		"@context": "https://schema.org",
		"@type":    "WebSite",
		"name":     "arehman.dev",
		"url":      canonical("/"),
	})
}

func personLD() template.HTML {
	return ldScript(map[string]any{
		"@context": "https://schema.org",
		"@type":    "Person",
		"name":     authorName,
		"url":      canonical("/"),
		"sameAs":   authorSameAs,
	})
}

func blogPostingLD(p *content.Post) template.HTML {
	author := map[string]any{"@type": "Person", "name": authorName, "url": canonical("/")}
	m := map[string]any{
		"@context":         "https://schema.org",
		"@type":            "BlogPosting",
		"headline":         p.Title,
		"author":           author,
		"publisher":        author,
		"mainEntityOfPage": map[string]any{"@type": "WebPage", "@id": canonical("/posts/" + p.Slug)},
	}
	if p.Description != "" {
		m["description"] = p.Description
	}
	if !p.Date.IsZero() {
		m["datePublished"] = p.Date.UTC().Format(time.RFC3339)
	}
	return ldScript(m)
}

// breadcrumbLD emits a two-level trail (Home › current page). The current page
// is the last crumb and carries no "item" per Google's spec.
func breadcrumbLD(title, path string) template.HTML {
	return ldScript(map[string]any{
		"@context": "https://schema.org",
		"@type":    "BreadcrumbList",
		"itemListElement": []map[string]any{
			{"@type": "ListItem", "position": 1, "name": "Home", "item": canonical("/")},
			{"@type": "ListItem", "position": 2, "name": title},
		},
	})
}
